<a href="https://colab.research.google.com/github/kimberlyhinoztrozaolg/unidad1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy es una libreria de python.
numpy se utiliza para trabajar con matrices o arreglos
numpy es la abreviatura de "python numerico"
tambien tiene funciones para trabajar en el dominio de algebra lineal, la transformada y las matrices
en python tenemos listas que sirven como matrices, pero son lentas de procesar.
numpy tiene como objetivo proporcionar un objeto de matriz que sea 50 veces mas rapido que las listas tradicionales.

In [1]:
#primero tenemos que importar la libreria
import numpy

arreglo = numpy.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


numpy como np
numpy generalmente se importa bajo el alias np. en python los alias son un nombre alternativo para referirse a la misma cosa

In [2]:
import numpy as np

arreglo = np.array([6,7,8,9,10])
print (arreglo)

[ 6  7  8  9 10]


comprobando la version numpy
la cadena de la version se almacena en el atributo__version__

In [3]:
import numpy as np

print(np.__version__)

2.0.2


numpy creando matrices
crear un objeto ndarray de numpy
numpy se utiliza para trabajar con matrices. el objeto de matriz se llama ndarray.
podemos cear un numpy ndarray utilizando la funcion array()

In [4]:
import numpy as np

arreglo = np.array(["kimi" , "vicente" , "mamango" , "aitana"])
print(arreglo)
print(type(arreglo))

['kimi' 'vicente' 'mamango' 'aitana']
<class 'numpy.ndarray'>


dimensiones en matrices
una dimension en matrices es un nivel de profundidad de matriz (matrices anidadas)
una martriz anidada contiene matrices como elementos
matrices 0-D. son elementos de una matriz. cada valor deuna matriz es una matriz 0-D. ejemplo: crea una matriz 0-D con un valor de 42

In [5]:
import numpy as np

arreglo = np.array(42)
print(arreglo)

42


matrices 1-D
una matriz que tiene matrices 0-D como elementos se denomina como matriz unidimensonal o 1-D.
estas son las matrices mas comunes y basicas.
ejemplo: crea una matris de 1-D que tenga los valores 1,2,3,4,5

In [7]:
import numpy as np

arreglo = np.array([1,2,3,4,5])

print(arreglo)

[1 2 3 4 5]


matrices 2D
una matriz que tiene matrices 1-D como elementos se denmina matriz 2-D.
a menudo se utiliza para representar matrices de segundo orden. numpy tiene un submodulo completo dedicado a operaciones con matrices llamado numpyt.mat
ejemplo: crea una matriz 2D que contenga dos matrices con los valores 123 y 456

In [8]:
import numpy as np

arreglo = np.array([[1,2,3],[4,5,6]])

print(arreglo)

[[1 2 3]
 [4 5 6]]


matrices 3D
una matriz que tiene matrices 2-D se denomina 3-D.
estas matrices se utilizan para representar una matris de tercer orden.
ejemplo: crea una matriz de 3D con dos matrices bidimensioales, ambas conteniendo dos matrices con los valores 1,2,3 y 4,5,6.

In [9]:
import numpy as np

arreglo = np.array([[[1,2,3] , [4,5,6]] , [[1,2,3],[4,5,6]]])

print(arreglo)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
